---
title: "Sensitivity check"
author: "Sarah Nadeau"
date: "16/04/2021"
output: html_document
---

Sensitivity of chain descriptions to different chain definitions.

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/nadeaus/Repos/grapevine")
knitr::opts_chunk$set(root.dir = "/Users/nadeaus/Repos/grapevine")
require(dplyr)
require(ggplot2)
require(ggtree)
```

```{r}
source("generate_figures/functions.R")
source("generate_alignments/functions.R")
source("database/R/utility.R")
source("utility_functions.R")
db_connection = open_database_connection()
```

## Load base data

```{r}
workdir <- paste(
  "/Users/nadeaus/Repos/cov-swiss-phylogenetics/results_all/validation",
  "accuracy_validation",
  sep = "/")
bag_exposures <- get_bag_exposures(db_connection = db_connection)
metadata <- load_sample_metadata(workdir = workdir)
```

## Load specific data

```{r}
min_chain_size <- 1
m_p_vals <- c("m_0_p_0", "m_0_p_1", "m_1_p_1", "m_2_p_1", "m_3_p_1")

# LEFT OFF HERE: not loading all results correctly
is_first <- T
for (m_p_val in m_p_vals) {
  chains <- rbind(
    load_chain_asr_data(
      s = F, workdir = workdir, 
      chains_only = T, chains_dirname = paste("chains", m_p_val, sep = "_")) %>%  
      filter(size >= min_chain_size) %>%
      mutate(
        chain_idx = 1:n(),
        chains_assumption = "max",
        tree = gsub(tree, pattern = "_s_F|_s_T", replacement = "")),
    load_chain_asr_data(
      s = T, workdir = workdir,
      chains_only = T, chains_dirname = paste("chains_m", m, "p", p, sep = "_")) %>%  
      filter(size >= min_chain_size) %>%
      mutate(
        chain_idx = 1:n(),
        chains_assumption = "min",
        tree = gsub(tree, pattern = "_s_F|_s_T", replacement = ""))
  ) %>% mutate(chain_defn = m_p_val)
  if (is_first) {
    is_first <- F
    chains_all <- chains
  } else {
    chains_all <- rbind(chains, chains_all)
  }
}
```

## Calculate statistics & accuracy under different transmission chain definitions

```{r}
validation_results <- samples %>% 
  group_by(chains_assumption, chain_idx) %>% 
  summarize(
    n_foreign_exposures = length(iso_country_exposure[iso_country_exposure != "CHE"]),
    n_diff_foreign_exposures = length(unique(iso_country_exposure[iso_country_exposure != "CHE"])))

validation_results %>% 
  group_by(chains_assumption, n_diff_foreign_exposures) %>%
  summarize(n_chains = n()) %>%
  arrange(chains_assumption, n_diff_foreign_exposures)

validation_results %>% 
  group_by(chains_assumption) %>%
  summarize(
    n_incongruent_exposures = sum(n_diff_foreign_exposures > 1),
    n_exposed_chains = sum(n_foreign_exposures > 0),
    frac_incongruent_exposures = sum(n_diff_foreign_exposures > 1) / sum(n_foreign_exposures > 0))

validation_results %>%
  mutate(incongruent_foreign_exposures = n_diff_foreign_exposures > 1) %>%
  group_by(chains_assumption) %>%
  mutate(n_chains_total = n()) %>%
  group_by(chains_assumption, incongruent_foreign_exposures) %>%
  summarize(n_chains = n(), frac_chains = n() / n_chains_total[1])
```

Are the exposure samples typically among the first sampled in the chain?
```{r}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

validation_results_2 <- samples %>%
  group_by(chains_assumption, chain_idx) %>%
  arrange(date) %>%
  mutate(
    chain_rank = 1:n(),
    is_foreign_exposure = iso_country_exposure != "CHE")

validation_results_2 %>% 
  group_by(chains_assumption, is_foreign_exposure) %>%
  summarize(
    mean_rank = mean(chain_rank),
    med_rank = median(chain_rank),
    mode_rank = getmode(chain_rank))
```
