---
title: "Compare chains with different size context sets, different chain definitions"
author: "Sarah Nadeau"
date: "17/05/2021"
output: html_document
---

Note: I also tried running 5x and 10x size context sets, but Euler either timed out (5x) or ran out of memory (10x).

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/nadeaus/Repos/cov-swiss-phylogenetics")
knitr::opts_chunk$set(root.dir = "/Users/nadeaus/Repos/cov-swiss-phylogenetics")
```

```{r, include=FALSE}
require(dplyr)
require(ggplot2)
source("../grapevine/database/R/utility.R")
source("../grapevine/utility_functions.R")
source("../grapevine/generate_figures/functions.R")
source("scripts/figures_shared_vars.R")
```

# Load data

```{r}
load_results <- function(
  prefix = "results_all/jan-dec_-01_max_sampling_0_travel_",
  suffix = "_sim_context",
  reps = c("", "1", "2"),
  values = c("1", "2", "3")
) {
  results <- list()
  for (value in values) {
    for (rep in reps) {
      fp <- paste(prefix, value, suffix, case_when(rep == "" ~ rep, T ~ paste("_rep_", rep, sep = "")), sep = "")
      print(paste("Loading results in", fp))
      if (dir.exists(fp)) {
        res_desc <- paste(value, "x_rep", case_when(rep == "" ~ "0", T ~ rep), sep = "")
        results_temp <- load_grapevine_results(workdir = fp)
        results[[res_desc]] <- results_temp
      } else {
        warning(paste("Directory", fp, "does not exist."))
      }
    }
  }
  return(results)
}

results <- load_results()
```

# Compare transmission chain summary statistics across context set sizes, chains assumption

```{r}
is_first <- T
for (i in 1:length(results)) {
  res_desc <- names(results)[i]
  chains_temp <- results[[i]]$chains %>% mutate(res_desc = res_desc)
  if (is_first) {
    is_first <- F
    chains_all <- chains_temp
  } else {
    chains_all <- rbind(chains_all, chains_temp)
  }
}

to_plot <- chains_all %>%
  tidyr::separate(res_desc, into = c("sim_context", "rep"), sep = "x_rep") %>%
  mutate(sim_context = as.numeric(sim_context), rep = as.numeric(rep)) %>%
  group_by(sim_context, rep, chains_assumption) %>%
  summarize(
    mean_size = mean(size),
    median_size = median(size),
    number_chains = n(),
    number_trees = length(unique(tree)),
    .groups = "drop")

to_plot_w_runtime <- merge(
  x = to_plot,
  y = data.frame(
    sim_context = c(rep(1, 3), rep(2, 3), rep(3, 3)),
    rep = c(rep(0:2, 3)),
    runtime_sec = c(13009, 10835, 11214, 11612, 11666, 11282, 20983, 26932, 27302)))  # collated from Euler job finished emails, see data/runtimes.pdf

ggplot(
  data = to_plot_w_runtime,
  aes(x = sim_context, shape = as.character(rep))) + 
  geom_point(aes(y = mean_size, color = "Mean chain size")) + 
  geom_point(aes(y = median_size, color = "Median chain size")) + 
  geom_point(aes(y = number_chains / 10, color = "Number chains / 10")) + 
  geom_point(aes(y = runtime_sec / 60^2, color = "Runtime (hours)")) + 
  # geom_point(aes(y = number_trees / 5, color = "Number lineage trees / 5")) + 
  facet_grid(. ~ chains_assumption, labeller = as_labeller(chain_assumption_labs)) + 
  shared_theme + 
  scale_shape(name = "Replicate") + 
  scale_color_discrete(name = "Value") + 
  scale_x_continuous(breaks = c(1, 2, 3), labels = c("1:1", "2:1", "3:1")) + 
  labs(x = "Ratio of foreign context to focal Swiss sequences", y = "Count")

ggsave(
  filename = "figures/fig_SX_sensitivity_context_set_size.png",
  width = double_col_width,
  height = single_col_width * 0.75, 
  units = "cm"
)
``` 

# Load alternate chain data for chosen context set ratio

```{r}
load_alternative_chains <- function(
  prefix = "results_all/jan-dec_-01_max_sampling_0_travel_",
  suffix = "_sim_context",
  reps = c("", "1", "2"),
  values = c("2")
) {
  is_first <- T
  for (value in values) {
    for (rep in reps) {
      fp <- paste(prefix, value, suffix, case_when(rep == "" ~ rep, T ~ paste("_rep_", rep, sep = "")), sep = "")
      print(paste("Loading alternative chain results in", fp))
      chain_dirs <- list.files(path = paste(fp, "tmp", sep = "/"), pattern = "chains_m")
      for (dir in chain_dirs) {
        chains_temp <- rbind(
          load_chain_asr_data(s = T, workdir = fp, chains_only = T, chains_dirname = dir) %>% mutate(chains_assumption = "min"),
          load_chain_asr_data(s = F, workdir = fp, chains_only = T, chains_dirname = dir) %>% mutate(chains_assumption = "max")) %>%
          mutate(chain_desc = dir, res_desc = paste(value, "x_rep", case_when(rep == "" ~ "0", T ~ rep), sep = ""))
        if (is_first) {
          alternative_chains_all <- chains_temp
          is_first <- F
        } else {
          alternative_chains_all <- rbind(alternative_chains_all, chains_temp)
        }
      }
    }
  }
  return(alternative_chains_all)
}

alternative_chains_all <- load_alternative_chains()
```

# Compare transmission chain summary statistics across chain definitions, chains assumption

```{r}
to_plot_2 <- alternative_chains_all %>%
  tidyr::separate(res_desc, into = c("sim_context", "rep"), sep = "x_rep") %>%
  tidyr::separate(chain_desc, into = c("m", "p"), sep = "_p_") %>%
  mutate(
    sim_context = as.numeric(sim_context), rep = as.numeric(rep),
    m = as.numeric(gsub(m, pattern = "chains_m_", replacement = "")), p = as.character(p)) %>%
  group_by(rep, m, p, chains_assumption) %>%
  summarize(
    mean_size = mean(size),
    median_size = median(size),
    number_chains = n(),
    number_trees = length(unique(tree)),
    .groups = "drop")

ggplot(
  data = to_plot_2,
  aes(x = m, shape = as.character(rep))) + 
  geom_point(aes(y = mean_size, color = "Mean chain size")) + 
  geom_point(aes(y = median_size, color = "Median chain size")) + 
  geom_point(aes(y = number_chains / 10, color = "Number chains / 10")) + 
  facet_grid(
    p ~ chains_assumption, 
    labeller = as_labeller(x = c("0" = "0", "1" = "1", "2" = "2", "3" = "3", "4" = "4", chain_assumption_labs))) + 
  shared_theme + 
  scale_shape(name = "Replicate") + 
  scale_color_discrete(name = "Value") + 
  scale_y_continuous(sec.axis = dup_axis(
    name = "Maximum consecutive exports in transmission chain",
    breaks = NULL, labels = NULL)) + 
  labs(x = "Maximum exported lineages in transmission chain", y = "Count")

ggsave(
  filename = "figures/fig_SX_sensitivity_chain_defn.png",
  width = double_col_width,
  height = single_col_width * 1.5, 
  units = "cm"
)
```

