---
title: "Sample descriptions"
author: "Sarah Nadeau"
date: "6/4/2021"
output: pdf_document
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/nadeaus/Repos/cov-swiss-phylogenetics")
knitr::opts_chunk$set(root.dir = "/Users/nadeaus/Repos/cov-swiss-phylogenetics")
```

```{r, include=FALSE}
require(dplyr)
require(ggplot2)
require(xtable)
source("../grapevine/database/R/utility.R")
source("../grapevine/utility_functions.R")
source("../grapevine/generate_figures/functions.R")
source("scripts/figures_shared_vars.R")
```

Load data

```{r}
workdir <- "results_main"
outdir <- paste(workdir, "output", sep = "/")
outdir <- "figures"
grapevine_results <- load_grapevine_results(
  workdir = workdir, 
  min_chain_size = 1,
  viollier_only = F)
samples <- grapevine_results$samples
metadata <- load_sample_metadata(workdir = "results_main")
swiss_downsampling <- read.csv(file = "results_main/tmp/alignments/swiss_downsampling_data.csv")
```

Load pangolin lineage table & format for supplement

```{r}
lineages_data <- read.csv("results_main/tmp/alignments/pangolin_lineages_aggregated.csv")
analyzed_lineages <- metadata %>%
  group_by(tree_pangolin_lineage) %>%
  summarize(
    n_focal_samples = sum(iso_country == "CHE"),
    n_context_samples = sum(iso_country != "CHE"))
lineage_data_summary <- merge(
  x = analyzed_lineages,
  y = lineages_data %>% select(pangolin_lineage, lineages_aggregated, n_lineages_aggregated, is_swiss_FALSE, is_swiss_TRUE),
  by.x = "tree_pangolin_lineage", by.y = "pangolin_lineage",
  all.x = T) %>%
  mutate("% lineage Swiss" = signif(is_swiss_TRUE * 100 / (is_swiss_TRUE + is_swiss_FALSE), digits = 2)) %>%
  select(tree_pangolin_lineage, n_focal_samples, lineages_aggregated, `% lineage Swiss`) %>%
  arrange(desc(n_focal_samples)) %>%
  rename(
    "Lineage analyzed" = tree_pangolin_lineage,
    "Lineages aggregated" = lineages_aggregated,
    "No. Swiss samples analyzed" = n_focal_samples)

x_lineage_data_summary <- xtable(
  x = lineage_data_summary,
  caption = "Summary of Pango lineages analyzed. A separate phylogeny was constructed for each set of analyzed lineages.",
  label = "tab:lineage-data-summary",
  align = "llcp{4cm}c")
print(
  x = x_lineage_data_summary,
  type = "latex",
  file = "figures/lineage_data_summary.tex",
  floating = F,
  tabular.environment="longtable")
write.csv(
  x = lineage_data_summary, 
  file = "figures/lineage_data_summary.csv")
```

Summarize data

```{r}
sample_summary <- metadata %>%
  tidyr::pivot_longer(
    cols = c(travel_context, similarity_context, focal_sequence),
    names_to = "sequence_set",
    values_to = "in_sequence_set") %>%
  group_by(sequence_set) %>%
  summarize(
    n_samples = sum(in_sequence_set),
    n_swiss_samples = sum(in_sequence_set & iso_country == "CHE"))

swiss_downsampling_summary <- swiss_downsampling %>%
  group_by(week) %>%
  summarize(
    n_samples = sum(n_to_sample),
    n_cases = sum(n_conf_cases)) %>%
  mutate(empirical_sampling_proportion = n_samples / n_cases)
```

Write out stats for paper

```{r}
con <- file("manuscript/sample_summary_variables.tex", open = "w")

n_focal_sequences <- unlist(
  sample_summary %>% 
    filter(sequence_set == "focal_sequence") %>% 
    select(n_samples))
writeLines(text = paste0("\\newcommand\\nfocalsamples{", n_focal_sequences, "}"), con = con)

n_similarity_context_sequences <- unlist(
  sample_summary %>% 
    filter(sequence_set == "similarity_context") %>% 
    select(n_samples))
writeLines(text = paste0("\\newcommand\\nsimcontext{", n_similarity_context_sequences, "}"), con = con)

n_travel_context_sequences <- unlist(
  sample_summary %>% 
    filter(sequence_set == "travel_context") %>% 
    select(n_samples))
writeLines(text = paste0("\\newcommand\\ntravelcontext{", n_travel_context_sequences, "}"), con = con)

mean_weekly_sampling_per <- signif(mean(swiss_downsampling_summary$empirical_sampling_proportion) * 100, 2)
writeLines(text = paste0("\\newcommand\\meanweeklysamplingpercent{", mean_weekly_sampling_per, "}"), con = con)

min_weekly_sampling_per <- signif(min(swiss_downsampling_summary$empirical_sampling_proportion) * 100, 2)
writeLines(text = paste0("\\newcommand\\minweeklysamplingpercent{", min_weekly_sampling_per, "}"), con = con)

max_weekly_sampling_per <- signif(max(swiss_downsampling_summary$empirical_sampling_proportion) * 100, 2)
writeLines(text = paste0("\\newcommand\\maxweeklysamplingpercent{", max_weekly_sampling_per, "}"), con = con)

overall_sampling_per <- signif(sum(swiss_downsampling$n_to_sample) / sum(swiss_downsampling$n_conf_cases) * 100, 2)
writeLines(text = paste0("\\newcommand\\overallsamplingpercent{", overall_sampling_per, "}"), con = con)
close(con)
```