---
title: "Fig. 1"
output: pdf_document
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/nadeaus/Repos/cov-swiss-phylogenetics")
knitr::opts_chunk$set(root.dir = "/Users/nadeaus/Repos/cov-swiss-phylogenetics")
```

```{r, include=FALSE}
source("../grapevine/database/R/utility.R")
source("../grapevine/utility_functions.R")
source("../grapevine/generate_figures/functions.R")
require(dplyr)
require(ggplot2)
```

Define shared variables

```{r}
chain_assumption_labs <- c("Smallest plausible chains", "Largest plausible chains")
names(chain_assumption_labs) <- c("max", "min")
shared_theme <- theme_bw()
single_col_width <- 11.4  # cm
n_chains_to_plot <- 10
wave_break <- as.Date("2020-05-01")
```

Load external data

```{r}
# source: https://ourworldindata.org/grapher/covid-stringency-index
stringency_index <- read.csv(file = "data/covid-stringency-index.csv") %>%
  filter(Code == "CHE")
```

Load data

```{r}
workdir <- "results_main"
grapevine_results <- load_grapevine_results(
  workdir = workdir, 
  min_chain_size = 1,
  viollier_only = F)
samples <- grapevine_results$samples
```

Summarize data

```{r}
chain_summary_stats <- samples %>%
  mutate(sample_month = format(date, "%Y-%m-01")) %>%
  group_by(chains_assumption, tree, chain_idx, sample_month) %>%
  summarize(n_samples = n()) 

chains_to_highlight <- samples %>%
  mutate(wave = date <= wave_break) %>%
  group_by(chains_assumption, tree, chain_idx, wave) %>%
  summarize(n_samples_chain = n()) %>%
  ungroup() %>%
  group_by(chains_assumption, wave) %>%
  top_n(n = n_chains_to_plot, wt = n_samples_chain) %>%
  tidyr::unite(col = "chain_to_plot", tree, chain_idx, remove = F) %>%
  select(-n_samples_chain)

chain_summary_stats <- merge(
  x = chain_summary_stats, 
  y = chains_to_highlight,
  all = T) 

chain_summary_stats <- chain_summary_stats %>% 
  group_by(sample_month, chains_assumption, chain_to_plot) %>%
  summarize(n_samples = sum(n_samples)) %>%
  ungroup() %>%
  tidyr::complete(
    sample_month, chains_assumption, chain_to_plot, 
    fill = list(n_samples = 0)) %>%
  tidyr::separate(
    col = chain_to_plot, 
    into = c("pango_lineage", "m", "m_val", "p", "p_val", "chain_idx"),
    sep = "_", 
    remove = F) %>%
  select(-c(m, m_val, p, p_val, chain_idx)) %>%
  tidyr::replace_na(
    replace = list("pango_lineage" = "Smaller chain"))
```

Make plot

```{r}
scale_factor <- 0.01
p <- ggplot() + 
  geom_area(
    data = chain_summary_stats,
    aes(
      x = as.Date(sample_month), 
      y = n_samples,
      group = chain_to_plot, fill = pango_lineage),
    position = "fill", 
    stat = "identity") +  # show legend
  geom_area(
    data = chain_summary_stats,
    aes(
      x = as.Date(sample_month), 
      y = n_samples,
      group = chain_to_plot, fill = pango_lineage),
    position = "fill", 
    stat = "identity",
    colour = "black", show.legend = F) +  # don't show black outline in legend
  geom_line(
    data = stringency_index %>% 
      filter(
        as.Date(Day) <= max(chain_summary_stats$sample_month),
        as.Date(Day) >= min(chain_summary_stats$sample_month)),
    aes(x = as.Date(Day), y = stringency_index * scale_factor, size = "Stringency index")) +
  scale_y_continuous(
    sec.axis = sec_axis( trans = ~./scale_factor, name = "Stringency index")) +
  scale_x_date(date_labels = "%b. %Y", date_breaks = "1 month") + 
  facet_wrap(
    chains_assumption~.,
    nrow = 2,
    labeller = labeller(chains_assumption = chain_assumption_labs),
    strip.position = "top")

pango_lineages <- unique(chain_summary_stats$pango_lineage)[
  unique(chain_summary_stats$pango_lineage) != "Smaller chain"]
lineage_colors <- c(
  RColorBrewer::brewer.pal(n = length(pango_lineages), name = "Paired"),
  "grey50")
names(lineage_colors) <- c(
  pango_lineages,
  "Smaller chain")

pretty_p <- p + 
  labs(
    x = element_blank(),
    y = "Fraction of samples") +
  scale_fill_manual(
    name = "PANGO lineage",
    values = lineage_colors) + 
  scale_size_manual(
    values = c("Stringency index" = 1),
    name = element_blank()) + 
  shared_theme +
  theme(
    legend.position = "right",
    axis.text.x = element_text(angle = 90, vjust = 0.5))

show(pretty_p)
```

Save plot

```{r}
ggsave(
  plot = pretty_p,
  file = paste("figures", "fig_1_chains_through_time.png", sep = "/"),
  width = single_col_width,
  height = single_col_width,
  units = "cm"
)
```
