---
title: "Plot introductions vs. European incidence"
author: nadeaus
date: 12.10.21
output: html_notebook
---

This script is to see if the relationship between Europe-wide incidence and estimated imports into Switzerland changes upon the Swiss border closures.

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/nadeaus/Repos/cov-swiss-phylogenetics")
knitr::opts_chunk$set(root.dir = "/Users/nadeaus/Repos/cov-swiss-phylogenetics")
```

```{r, include=FALSE}
require(dplyr)
require(tidyr)
require(ggplot2)
require(cowplot)
source("../sars_cov_2/grapevine/database/R/utility.R")
source("../sars_cov_2/grapevine/utility_functions.R")
source("../sars_cov_2/grapevine/generate_figures/functions.R")
source("scripts/figures_shared_vars.R")
```

Load grapevine data

```{r}
workdir <- "results_main"
outdir <- paste(workdir, "output", sep = "/")
outdir <- "figures"
grapevine_results <- load_grapevine_results(
  workdir = workdir,
  min_chain_size = 1,
  viollier_only = F)
```

Load case data for European countries

```{r}
CASE_COUNT_LINK <- "https://covid.ourworldindata.org/data/owid-covid-data.csv"  # early data for France not very good
CASE_COUNT_LINK <- "https://opendata.ecdc.europa.eu/covid19/casedistribution/csv/"
cases_raw <- read.csv(url(CASE_COUNT_LINK), na.strings = "", fileEncoding = "UTF-8-BOM") %>%
  filter(continentExp == "Europe") %>%
  select(countryterritoryCode, dateRep, cases) %>%
  mutate(date = as.Date(dateRep, "%d/%m/%Y")) %>%
  filter(date <= as.Date("2020-12-01"))

cases_summary <- cases_raw %>%
        mutate(country = case_when(
                countryterritoryCode == "CHE" ~ "Switzerland",
                countryterritoryCode == "FRA" ~ "France",
                countryterritoryCode == "DEU" ~ "Germany",
                countryterritoryCode == "ITA" ~ "Italy",
                T ~ "Other European")) %>%
        group_by(date, country) %>%
        summarize(cases = sum(cases), .groups = "drop") %>%
        group_by(country) %>%
        arrange(date) %>%
        mutate(weekly_avg_new_cases = zoo::rollmean(cases,7, align = "center", na.pad = T))
```

Plot case data vs. introductions

```{r}
chain_summary_stats <- grapevine_results$samples %>%
        group_by(tree, chains_assumption, chain_idx) %>%
        summarize(first_sample_date = min(date), .groups = "drop") %>%
        full_join(y = grapevine_results$chains, by = c("tree", "chains_assumption", "chain_idx"))

dummy_data <- rbind(
        data.frame(
                date = seq.Date(as.Date("2020-01-01"), as.Date("2020-12-01"), "day"),
                chains_assumption = "min"),
        data.frame(
                date = seq.Date(as.Date("2020-01-01"), as.Date("2020-12-01"), "day"),
                chains_assumption = "max"))

introduction_summary_stats_1 <- chain_summary_stats %>%
        group_by(first_sample_date, chains_assumption) %>%
        summarise(introductions_by_first_sample_date = n()) %>%
        mutate(date = as.Date(first_sample_date)) %>%
        right_join(dummy_data, by = c("date", "chains_assumption")) %>%
        mutate(introductions_by_first_sample_date = replace_na(introductions_by_first_sample_date, 0)) %>%
        arrange(chains_assumption, date) %>%
        group_by(chains_assumption) %>%
        mutate(country = "Switzerland",
               weekly_avg_introductions_by_first_sample_date = zoo::rollmean(introductions_by_first_sample_date, 7, align = "center", na.pad = T))
introduction_summary_stats_2 <- chain_summary_stats %>%
        group_by(tmrca, chains_assumption) %>%
        summarise(introductions_by_tmrca = n()) %>%
        mutate(date = as.Date(tmrca)) %>%
        right_join(dummy_data, by = c("date", "chains_assumption")) %>%
        mutate(introductions_by_tmrca = replace_na(introductions_by_tmrca, 0)) %>%
        arrange(chains_assumption, date) %>%
        group_by(chains_assumption) %>%
        mutate(country = "Switzerland",
               weekly_avg_introductions_by_tmrca = zoo::rollmean(introductions_by_tmrca, 7, align = "center", na.pad = T))

introduction_summary <- full_join(
        x = introduction_summary_stats_1, y = introduction_summary_stats_2,
        by = c("date", "country", "chains_assumption"))

introduction_summary_wide <- introduction_summary %>%
        pivot_wider(names_from = "chains_assumption", values_from = c(
                "introductions_by_first_sample_date",
                "weekly_avg_introductions_by_first_sample_date",
                "introductions_by_tmrca",
                "weekly_avg_introductions_by_tmrca"))

combined_data <- cases_summary %>% full_join(introduction_summary_wide, by = c("date", "country"))

country_fill_scale <- scale_fill_manual(
  values = c("Switzerland" = "#E69F00", "France" = "#56B4E9", "Germany" = "#F0E442", "Italy" = "#009E73", "Other European" = "#CC79A7"),
  name = element_blank())

incidence_plot <- ggplot(data = combined_data %>%
        filter(date <= as.Date("2020-06-15"), date >= "2020-02-15"),
        aes(x = date, fill = country)) +
        geom_col(aes(y = weekly_avg_new_cases), position = "dodge") +
        # geom_label(data = . %>% group_by(metric) %>% filter(value == max(value, na.rm = T)), aes(label = date)) +  # label maximum point
        scale_x_date(date_breaks = "1 month", date_labels = "%b.") +
        labs(y = "Confirmed cases\n(weekly average)", x = "") +
        shared_theme +
        country_fill_scale +
        geom_vline(xintercept = as.Date("2020-03-13"), linetype = "dashed")

introductions_plot <- ggplot(data = combined_data %>%
        filter(country == "Switzerland", date <= as.Date("2020-06-15"), date >= "2020-02-15"),
        aes(x = date)) +
        geom_errorbar(aes(ymin = weekly_avg_introductions_by_first_sample_date_min, ymax = weekly_avg_introductions_by_first_sample_date_max)) +
        scale_x_date(date_breaks = "1 month", date_labels = "%b.") +
        labs(y = "New introductions\n (weekly average)", x = "") +
        shared_theme +
        geom_vline(xintercept = as.Date("2020-03-13"), linetype = "dashed")

# Extract legend to plot seperately
incidence_legend <- get_legend(
  # create some space to the left of the legend
  incidence_plot +
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom") +
    guides(fill=guide_legend(nrow=2,byrow=TRUE)))
incidence_plot <- incidence_plot + theme(legend.position = "none")

main_plots <- align_plots(introductions_plot, incidence_plot, align = "vh",  axis = 'bt')
left_plots <- plot_grid(
  main_plots[[1]], main_plots[[2]],
  ncol = 1)

plot_grid(left_plots, incidence_legend, rel_heights = c(1, 0.2), ncol = 1)
ggsave("figures/introductions_vs_european_indicence.png",
       width = single_col_width, height = single_col_width, units = "cm")
```
