---
title: "Untitled"
author: "Sarah Nadeau"
date: "9/8/2021"
output: html_document
---

```{r }
library(tidyverse)
library(lubridate)
library(ggdist)
library(cowplot)
library(zoo)

source("scripts/figures_shared_vars.R")

datadir_che <- "results_all/bdsky/log_files/SwissTransmissionChains/results/"
datadir_nzl <- "results_all/bdsky/log_files/NZTransmissionChains/results/"
```

# Load CT data

```{r}
NZL_CT_data <- NULL
for (clusters in c("min", "max")) {
    for (contact_tracing in c(TRUE, FALSE)) {
        for (sampUB in c("With sampling bound", "Without sampling bound" )) {
            pattern <- paste0("Re_skyline.", clusters, "_chains",
                              ".sampUB", ifelse(sampUB=="With sampling bound", "0.4", "1.0"),
                              ".", ifelse(contact_tracing, "1", "0"),
                              ".*.log")
            print(pattern)

            data <- NULL
            for (f in dir(datadir_nzl, pattern, full.names=TRUE)) {
                data <- bind_rows(data, read_tsv(f) %>% slice_tail(prop=0.9))
            }

            NZL_CT_data <- bind_rows(
              NZL_CT_data,
              data %>%
                slice_tail(prop=0.9) %>%
                select(Sample, "CTFactor[0]", "CTFactor[1]") %>%
                pivot_longer(cols=2:3) %>%
                mutate(lessThanOne=(value<1.0)) %>%
                mutate(clusters=clusters,
                       contact_tracing=contact_tracing,
                       sampUB=sampUB))
        }
    }
}

NZL_CT_data <- NZL_CT_data %>%
  mutate(season = case_when(
    name == "CTFactor[0]" ~ "After 15. May",
    name == "CTFactor[1]" ~ "Before 15. May"), 
  season = factor(season, levels = c("Before 15. May", "After 15. May")))

CHE_CT_data <- NULL
for (clusters in c("min", "max")) {
    for (contact_tracing in c(TRUE, FALSE)) {
        for (sampUB in c("With sampling bound", "Without sampling bound" )) {
            pattern <- paste0("Re_skyline.", clusters, "_chains",
                              ".sampUB", ifelse(sampUB=="With sampling bound", "0.05", "1.0"),
                              ".", ifelse(contact_tracing, "1", "0"),
                              ".*.log")
            
            data <- NULL
            for (f in dir(datadir_che, pattern, full.names=TRUE)) {
              data <- bind_rows(data, read_tsv(f) %>% slice_tail(prop=0.9))
            }
            
            CHE_CT_data <- bind_rows(
              CHE_CT_data,
              data %>%
                slice_tail(prop=0.9) %>%
                select(Sample, "CTFactor[0]", "CTFactor[1]", "CTFactor[2]") %>%
                pivot_longer(cols=2:4) %>%
                mutate(lessThanOne=(value<1.0)) %>%
                mutate(clusters=clusters,
                       contact_tracing=contact_tracing,
                       sampUB=sampUB))
        }
    }
}

CHE_CT_data <- CHE_CT_data %>%
  mutate(season = case_when(
    name == "CTFactor[0]" ~ "Fall",
    name == "CTFactor[1]" ~ "Summer",
    name == "CTFactor[2]" ~ "Spring"), 
  season = factor(season, levels = c("Spring", "Summer", "Fall")))
```

## Combine NZL and CHE data

```{r}
CT_data <- rbind(NZL_CT_data %>% mutate(country = "New Zealand"),
                 CHE_CT_data %>% mutate(country = "Switzerland")) %>%
  mutate(country = factor(country, levels = c("Switzerland", "New Zealand")),
         transmission_rate_decrease = (1 - value) * 100)
```

## Load case data

```{r}
CASE_COUNT_LINK <- "https://covid.ourworldindata.org/data/owid-covid-data.csv"
cases <- read.csv(url(CASE_COUNT_LINK)) %>%
  filter(location == "Switzerland") %>%
  select(date, new_cases) %>%
  group_by(date) %>%
  summarize(new_cases = sum(new_cases, na.rm = T)) %>%
  arrange(date) %>%
  mutate(weekly_average_new_cases = zoo::rollmean(x = new_cases, k = 7, na.pad = T)) %>%
  mutate(date = as.Date(date),
         season = case_when(date < as.Date("2020-06-15") ~ "Spring",
                            date <= as.Date("2020-09-30") ~ "Summer",
                            date <= as.Date("2020-12-31") ~ "Fall"),
         season = factor(season, levels = c("Spring", "Summer", "Fall")))

cases_nzl <- read.csv(url(CASE_COUNT_LINK)) %>%
  filter(location == "New Zealand") %>%
  select(date, new_cases) %>%
  group_by(date) %>%
  summarize(new_cases = sum(new_cases, na.rm = T)) %>%
  arrange(date) %>%
  mutate(weekly_average_new_cases = zoo::rollmean(x = new_cases, k = 7, na.pad = T)) %>%
  mutate(date = as.Date(date),
         season = case_when(date < as.Date("2020-05-15") ~ "Before 15. May",
                            date <= as.Date("2020-12-31") ~ "After 15. May"),
         season = factor(season, levels = c("Before 15. May", "After 15. May")))
```

## Plot CT damping and case data for comparison

```{r}
CT_data_main_text <- CT_data %>% filter(contact_tracing == "TRUE", sampUB == "Without sampling bound")

binwidth <- 3
nzl_early_col <- RColorBrewer::brewer.pal(n = 8, name = "PuRd")[[3]]
nzl_late_col <- RColorBrewer::brewer.pal(n = 8, name = "YlGn")[[3]]

# Swiss CT
ct <- ggplot(
  data = CT_data_main_text %>% filter(country == "Switzerland"),
  aes(x = transmission_rate_decrease, alpha = clusters)) + 
  geom_histogram(binwidth = binwidth) + 
  facet_grid(. ~ season) + 
  scale_alpha_manual(values = c(0.5, 0.85), labels = chain_assumption_labs, name = chains_assumption_legend_name) + 
  labs(x = ct_factor_x_lab, y = ct_factor_y_lab) + 
  shared_theme
# Extract legend to plot seperately
ct_legend <- get_legend(
  # create some space to the left of the legend
  ct +
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom"))
ct <- ct + theme(legend.position = "none")

# New Zealand CT
# There's a warning about 4 rows containing missing values when x-scaled forced to go down to zero 
# but all bars appear identical to when x-scale not forced 
ct_nzl <- ggplot(
  data = CT_data_main_text %>% filter(country == "New Zealand"),
  aes(x = transmission_rate_decrease, alpha = clusters)) + 
  geom_histogram(binwidth = binwidth) + 
  facet_grid(. ~ season) + 
  scale_alpha_manual(values = c(0.5, 0.85), labels = chain_assumption_labs, name = chains_assumption_legend_name) + 
  labs(x = ct_factor_x_lab, y = ct_factor_y_lab) +
  shared_theme + 
  lims(x = c(0, NA)) + 
  theme(legend.position = "none")

# Change facet strip colors: https://stackoverflow.com/questions/19440069/ggplot2-facet-wrap-strip-color-based-on-variable-in-data-set
g <- ggplot_gtable(ggplot_build(ct))
stripr <- which(grepl('strip-t', g$layout$name))
fills <- c(spring_col, summer_col, fall_col)
k <- 1
for (i in stripr) {
  j <- which(grepl('rect', g$grobs[[i]]$grobs[[1]]$childrenOrder))
  g$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  k <- k+1
}

g_nzl <- ggplot_gtable(ggplot_build(ct_nzl))
stripr <- which(grepl('strip-t', g_nzl$layout$name))
fills <- c(nzl_early_col, nzl_late_col)
k <- 1
for (i in stripr) {
  j <- which(grepl('rect', g_nzl$grobs[[i]]$grobs[[1]]$childrenOrder))
  g_nzl$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  k <- k+1
}

case_plot <- ggplot(
  data = cases %>% filter(date >= as.Date("2020-02-01"), date <= as.Date("2020-11-30")),
  aes(x = date, y = weekly_average_new_cases, fill = season)) + 
  geom_col() + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b", expand = c(0, 3)) + 
  scale_fill_manual(values = c("Spring" = spring_col, "Summer" = summer_col, "Fall" = fall_col)) + 
  labs(x = element_blank(), y = "New cases") + 
  shared_theme + 
  theme(legend.position = "none") + 
  ggtitle("Switzerland")

case_plot_nzl <- ggplot(
  data = cases_nzl %>% filter(date >= as.Date("2020-02-01"), date <= as.Date("2020-11-30")),
  aes(x = date, y = weekly_average_new_cases, fill = season)) + 
  geom_col() + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b", expand = c(0, 3)) + 
  scale_fill_manual(values = c("Before 15. May" = nzl_early_col, "After 15. May" = nzl_late_col)) + 
  labs(x = element_blank(), y = "New cases") + 
  shared_theme + 
  theme(legend.position = "none") + 
  ggtitle("New Zealand")

col_1_plots <- align_plots(case_plot, g, align = 'v', axis = 'bt')
col_2_plots <- align_plots(case_plot_nzl, g_nzl, align = "v", axis = "bt")

top_row <- plot_grid(
  col_1_plots[[1]], col_2_plots[[1]],
  labels = c("A", "B"),
  rel_widths = c(1, 1),
  nrow = 1)

bottom_row <- plot_grid(
  col_1_plots[[2]], col_2_plots[[2]],
  labels = c("C", "D"),
  rel_widths = c(3, 2.1),
  nrow = 1)

# then combine with the top row for final plot
plot_grid(top_row, bottom_row, ct_legend, rel_heights = c(1, 1, 0.3), ncol = 1)

ggsave("figures/contact_tracing_factors_no_sampUB_compared_to_cases.pdf",
       width = double_col_width, height = single_col_width, units = "cm")
```

## All-analyses damping factor figure for supplemental

```{r}
nzl_ct_supp <- ggplot() +  
  geom_histogram(
    data = CT_data %>% filter(country == "New Zealand", contact_tracing == "TRUE", clusters == "max"), 
    aes(x = transmission_rate_decrease, fill = clusters), alpha = 0.5, bins = 30) + 
  geom_histogram(
    data = CT_data %>% filter(country == "New Zealand", contact_tracing == "TRUE", clusters == "min"), 
    aes(x = transmission_rate_decrease, fill = clusters), alpha = 0.5, bins = 30) + 
  facet_grid(season ~ sampUB) + 
  scale_fill_manual(values = chains_assumption_colors, labels = chain_assumption_labs, name = chains_assumption_legend_name) + 
  shared_theme + 
  lims(x = c(-5, NA)) + 
  labs(x = ct_factor_x_lab, y = ct_factor_y_lab)

che_ct_supp <- ggplot() +  
  geom_histogram(
    data = CT_data %>% filter(country == "Switzerland", contact_tracing == "TRUE", clusters == "max"),
    aes(x = transmission_rate_decrease, fill = clusters), alpha = 0.5, bins = 30) + 
  geom_histogram(
    data = CT_data %>% filter(country == "Switzerland", contact_tracing == "TRUE", clusters == "min"), 
    aes(x = transmission_rate_decrease, fill = clusters), alpha = 0.5, bins = 30) + 
  facet_grid(season ~ sampUB) + 
  scale_fill_manual(values = chains_assumption_colors, labels = chain_assumption_labs, name = chains_assumption_legend_name) + 
  shared_theme + 
  lims(x = c(-5, NA)) + 
  labs(x = ct_factor_x_lab, y = ct_factor_y_lab)

# Arrange both plots together
require(cowplot)

legend <- get_legend(che_ct_supp)

plot_grid(
  che_ct_supp + theme(legend.position = "none"), 
  legend,
  nzl_ct_supp + theme(legend.position = "none"), 
  ncol = 2,
  rel_widths = c(1, 0.35),
  rel_heights = c(1.5, 1),
  width = double_col_width,
  labels = c("A", "", "B")
)

ggsave(
  filename = "figures/contact_tracing_factor_for_supp.png",
  width = double_col_width,
  height = single_col_width * 1.75,
  units = "cm"
)
```