---
title: "Validation dataset"
author: "Sarah Nadeau"
date: "28/04/2021"
output: html_document
---

Report validation data for supporting information.

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/nadeaus/Repos/grapevine")
knitr::opts_chunk$set(root.dir = "/Users/nadeaus/Repos/grapevine")
```

# Source functions, connect to database
```{r}
source("database/R/utility.R")
source("utility_functions.R")
source("generate_alignments/functions.R")
source("generate_figures/functions.R")
source("../cov-swiss-phylogenetics/scripts/figures_shared_vars.R")
db_connection = open_database_connection()
outdir <- "../cov-swiss-phylogenetics/figures"
```

# Load data
```{r}
exposure_sql <- "
-- get all samples with exposure recorded in BAG meldeformular (neglects those with info on GISAID from UniBasel)
select
vt.ethid,
si.gisaid_id,
bm.iso_country_exp,
bm.fall_dt,
c.name_english,
c.region
from bag_meldeformular bm
left join viollier_test vt on vt.sample_number = bm.sample_number
left join sequence_identifier si on si.ethid = vt.ethid
left join country c on c.iso_code = bm.iso_country_exp
where bm.iso_country_exp is not null
and iso_country_exp <> 'XXX'
and fall_dt > '2020-01-01' 
and fall_dt < '2021-01-01';"
bag_exposures <- DBI::dbGetQuery(
  conn = db_connection, statement = exposure_sql
)
  
bag_exposures_monthly <- bag_exposures %>%
  mutate(
    swiss_exposure = iso_country_exp == "CHE",
    month = format(fall_dt, "%Y-%m-01")) %>%
  group_by(month, swiss_exposure) %>%
  summarize(n_mkb_patients = n())

bag_exposure_locations <- bag_exposures %>% 
    mutate(region_w_switzerland = case_when(
      iso_country_exp == 'CHE' ~ "Switzerland",
      region == "Europe" ~ "other Europe",
      T ~ region
    )) %>%
    mutate(region_w_switzerland = factor(
      x = region_w_switzerland,
      levels = c("Africa", "Asia", "North America", "other Europe", "South America", "Switzerland"))) %>%
    group_by(region_w_switzerland) %>%
    summarize(n_mkb_patients = n())

incidence <- get_country_incidence(
  db_connection = db_connection, 
  min_date = as.Date("2020-01-01"), 
  max_date = as.Date("2020-12-31"),
  iso_countries = "CHE"
) %>%
  mutate(month = format(date, "%Y-%m-01")) %>%
  group_by(month) %>%
  summarize(new_cases = sum(new_cases))
```

# Plot reported exposures through time
```{r}
exposures_plot <- ggplot() + 
  geom_col(
    data = bag_exposures_monthly,
    aes(
      x = as.Date(month), 
      y = n_mkb_patients,
      fill = swiss_exposure)) + 
  geom_line(
    data = incidence,
    aes(
      x = as.Date(month),
      y = new_cases / 100,
      group = 1,
      linetype = "Confirmed cases / 100")) + 
  # geom_rect(
  #   data = incidence,
  #   alpha = 0.9,
  #   aes(
  #     xmin = as.Date("2020-05-11"),
  #     xmax = as.Date("2020-10-28"),
  #     ymin = 0, 
  #     ymax = max(new_cases / 100))) + 
  scale_x_date(
    date_labels = "%b. %Y", 
    date_breaks = "1 month",
    limits = c(as.Date("2020-01-01"), as.Date("2020-12-01"))) + 
  shared_theme +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
    legend.title = element_blank()) + 
  scale_fill_manual(
    values = list("FALSE" = "blue", "TRUE" = "red"),
    labels = list("FALSE" = "MKB exposure abroad", "TRUE" = "MKB exposure Switzerland")) + 

  labs(x = element_blank(), y = "Number of patients")

ggsave(
  plot = exposures_plot,
  file = paste(outdir, "fig_SX_mkb_exposures.png", sep = "/"),
  width = single_col_width / 2,
  height = single_col_width / 3
)

exposures_plot
```

# Plot reported exposure locations
```{r}
blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
)

exposure_locations_plot <- ggplot(
  data = bag_exposure_locations %>%
    arrange(desc(region_w_switzerland)) %>% 
    mutate(lab.ypos = cumsum(n_mkb_patients) - 0.5*n_mkb_patients),
  aes(x = "", y = n_mkb_patients, fill = region_w_switzerland)) + 
  geom_bar(stat = "identity") + 
  coord_polar("y", start = 0) + 
  blank_theme + 
  geom_text(
    aes(y = lab.ypos, x = 1.2, 
    label = n_mkb_patients)) + 
  theme(legend.title = element_blank(), 
        axis.title.y = element_blank(),
        axis.text.x = element_blank())

ggsave(
  plot = exposure_locations_plot,
  file = paste(outdir, "fig_SX_mkb_exposure_locations.png", sep = "/"),
  width = single_col_width / 2,
  height = single_col_width / 2
)

exposure_locations_plot
```

